migrate_source: "file://database/migration"

database:
  source: "postgresql://postgres:postgres@localhost:5432/you_mealdb?sslmode=disable"
  max_conns: 15
  min_conns: 0
  max_conn_life_time: 10m
  max_conn_idle_time: 5m
  health_check_period: 30s
  connect_timeout: 1m

redis_source: "redis://:@localhost:6379/0"
cache_category_ttl: 1m

recieving_ttl: 1h

image_path: "/images"

limit_category: 3

http_server:
  env: "local"
  address: "localhost:8080"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 30s
  max_header_bytes: 1048576

logs:
  env: "local"
  info_path: "logs/info.log"
  debug_path: "logs/debug.log"
  error_path: "logs/error.log"
  warn_path: "logs/warn.log"
  access_path: "logs/access.log"
  max_size: 100
  max_age : 30
  max_backups: 5 